In [19]:
from itertools import product
 

 
l = list(product(range(1, 5), repeat=2x\))



In [23]:
import numpy as np  

N = 5
adj_matrix = np.ones((N, N), dtype=int) 

In [24]:
adj_matrix

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
# set adj to ramdom values
adj_matrix = np.random.randint(0, 2, (N, N))

In [26]:
adj_matrix

array([[1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0],
       [0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1]])

In [27]:
neighbors_i = np.where(adj_matrix[2] == 1)[0].tolist()

In [28]:
neighbors_i

[2, 3]

In [36]:
adj_matrix[4,2] = 1

In [29]:
adj_matrix[:, 2]

array([0, 1, 1, 0, 0])

In [31]:
adj_matrix[2]

array([0, 0, 1, 1, 0])

In [32]:
np.where(adj_matrix[:,2] == 1)[0].tolist()

[1, 2]

In [37]:
i =2
j = 3

In [38]:
neighbors_i = np.where(adj_matrix[:,i] == 1)[0].tolist()
neighbors_j = np.where(adj_matrix[:,j] == 1)[0].tolist()
if j in neighbors_i:
    neighbors_i.remove(j)  # exclude j from neighbors
if i in neighbors_j:
    neighbors_j.remove(i)
# get the common neighbors
common_neighbors = set(neighbors_i).intersection(neighbors_j)

In [42]:
list(common_neighbors)

[4]